[application]
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "cowcord"
base_path = "/"

[web.build]
out_dir = "dist"

[web.watcher]
index_on_404 = true
reload = false

[profile.release.web.wasm_opt]
debug = false
level = "z"

[profile.beta.web.wasm_opt]
debug = false
level = 4

[bundle]
identifier = "fr.notacow"
publisher = "notacow"
